# Pack/Unpack

In [2]:
a,b,c = {1, 2, 3}
print(a,b,c)

1 2 3


In [ ]:
a = list(range(15))
print(a)
c,d,*e,f = a
# c = a[0]
# d = a[1]
# e = a[2...13]
# f = a[14]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [6]:
print(c)
print(d)
print(e)
print (f)

0
1
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
14


In [ ]:
a,*b=[1]
print(a) # a = 1
print(b) # b - empty

1
[]


In [ ]:
*b,=[1,2,3]
print(b)

[1, 2, 3]


In [10]:
*b, = []
print(b)

[]


In [ ]:
def g(a, b, c):
    print(a, b, c)
    return a + b

d = {'c' : 'asadasdas'}
g(1,b=2, **d)
# g(a=1,b=2,c='asadasdas')

1 2 asadasdas


3

In [18]:
print(*['a','b', 3])
print('a', 'b', 3)
print(['a', 'b', 3])

a b 3
a b 3
['a', 'b', 3]


# Function Ardguments

In [19]:
def func(*argv):
    print(type(argv))
    print(argv)

func(1,2,3)

<class 'tuple'>
(1, 2, 3)


In [21]:
def func(**karg):
    print(type(karg))
    print(karg)

func(a=1,b=2)

<class 'dict'>
{'a': 1, 'b': 2}


In [22]:
def func(*argv, **karg):
    print(type(argv))
    print(argv)
    print(type(karg))
    print(karg)

func(2,3,a=1,b=2)

<class 'tuple'>
(2, 3)
<class 'dict'>
{'a': 1, 'b': 2}


In [26]:
def func(a,b, *argv, g, **karg):
    print(type(argv))
    print(argv)
    print(type(karg))
    print(karg)
    print(g)
func(1,2,3,4,g=100,c=1,d=2)

<class 'tuple'>
(3, 4)
<class 'dict'>
{'c': 1, 'd': 2}
100


# Modules

In [28]:
import random
import random as rd # give allias (name) -> rd.get_rand()
print(type(random))
print(type(rd))

<class 'module'>
<class 'module'>


In [29]:
help(rd)

Help on module random:

NAME
    random - Random variable generators.

MODULE REFERENCE
    https://docs.python.org/3.13/library/random.html

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
        bytes
        -----
               uniform bytes (values between 0 and 255)

        integers
        --------
               uniform within range

        sequences
        ---------
               pick random element
               pick random sample
               pick weighted random sample
               generate random permutation

        distributions on the real line:
        ------------------------------
               uniform
               triangular
               normal (Gaussian)
               l

In [32]:
rd.randrange(10)

7

In [33]:
# import func from module + set name
from random import randrange as rdr
rdr(100)

66

![alt text](image.png)


In [34]:
def f(x):
    def g(x):
        return 1
    def k(x):
        return g(x)
    print(k(10))
print(f(1)) 

1
None


In [ ]:
def f():
    y = 1
    def g(x):
        print(2*y+1)
        return y
    g(1)
    return g # return g_func
w = f()
print(type(w))
w(1)

3
<class 'function'>
3


1

In [40]:
string = "12312sa d asd as dasdsad"
for i in range(0,len(string)):
    print(string[i])

1
2
3
1
2
s
a
 
d
 
a
s
d
 
a
s
 
d
a
s
d
s
a
d


In [38]:
string[2]='s'

TypeError: 'str' object does not support item assignment

In [43]:
print(string)
string = string[:2] + "sdasd" + string[3:]
print(string)

12312sa d asd as dasdsad
12sdasd12sa d asd as dasdsad


In [48]:
# можно как в C
a = 10
b = 4
string_1 = "a=%d" % (a)
print(string_1)

string_2 = "a={0} > b={1}".format(a,b)
print(string_2)

string_3 = "a={a} < b={b}".format(a=b, b=a)
print(string_3)

ctn=10
res=5
string_4 = f"ctn={ctn * 2 if res < 5 else ctn * 5}"
print(string_4)

a=10
a=10 > b=4
a=4 < b=10
ctn=50


# NumPy

In [49]:
import numpy as np

In [50]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
!dir # ! - запуск команды из cmd

 ��� � ���ன�⢥ C �� ����� ��⪨.
 ��਩�� ����� ⮬�: B2CC-8697

 ����ন��� ����� c:\dev\Source\LABS\Scientific _programming

29.10.2025  08:32    <DIR>          .
29.10.2025  08:32    <DIR>          ..
29.10.2025  08:32            31�762 image.png
29.10.2025  09:04            47�657 lesson_2025_10_09.ipynb
               2 䠩���         79�419 ����
               2 �����  40�487�178�240 ���� ᢮�����


In [52]:
!cd

c:\dev\Source\LABS\Scientific _programming


In [53]:
!pip list

Package                 Version
----------------------- -----------
anyio                   4.9.0
asttokens               3.0.0
certifi                 2025.6.15
charset-normalizer      3.4.2
colorama                0.4.6
comm                    0.2.3
comtypes                1.4.13
contourpy               1.3.2
cpplint                 2.0.2
cycler                  0.12.1
debugpy                 1.8.16
decorator               5.2.1
executing               2.2.1
filelock                3.19.1
fonttools               4.58.4
fsspec                  2025.7.0
h11                     0.16.0
httpcore                1.0.9
httpx                   0.28.1
idna                    3.10
ipykernel               6.30.1
ipython                 9.5.0
ipython_pygments_lexers 1.1.1
jedi                    0.19.2
Jinja2                  3.1.6
jupyter_client          8.6.3
jupyter_core            5.8.1
kiwisolver              1.4.8
MarkupSafe              3.0.2
matplotlib              3.10.3
matplotlib-inlin

In [54]:
a = [1,2,3,'4', 1.0]
a.append(1)
print(a)

[1, 2, 3, '4', 1.0, 1]


In [58]:
a = np.ones((10,14), dtype=np.int32)
print(a)
print(a.dtype)
print(type(a))

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
int32
<class 'numpy.ndarray'>


In [59]:
b = np.ones((10,14), dtype=np.int32)

In [60]:
a+b

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], dtype=int32)

In [61]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])