In [ ]:
import numpy as np
import random

In [15]:
%%timeit
ap = [random.randint(0,100) for i in range(0, 10000000)]

3.28 s ± 22.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
%%timeit
a = np.random.randint(100, size=(100000000), dtype=np.int32)

680 ms ± 19.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [21]:
a = np.random.randint(100, size=(100000000), dtype=np.int32)

In [22]:
a.nbytes

400000000

In [23]:
%%timeit
b = sum(a)

<magic-timeit>:1: RuntimeWarning: overflow encountered in scalar add


4.38 s ± 50.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
%%timeit
b = np.sum(a)

52.6 ms ± 914 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
4.38*1000.0/52.6

83.26996197718631

In [28]:
%%timeit
b = max(a)

3.67 s ± 59.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [30]:
%%timeit
b = np.max(a)

19.1 ms ± 1.18 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [31]:
%%timeit
n = 100000
a = []
for i in range(0, n):
    a.append(i)

3.32 ms ± 122 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [32]:
%%timeit
n = 100000
a = [x for x in range(0, n)]

2.45 ms ± 84.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
%%timeit
n = 10000000
a = sum(x for x in range(0, n))

319 ms ± 1.95 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [34]:
%%timeit
n = 1000000000
n = np.arange(n)
s = np.sum(n)

2.22 s ± 74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Vectoriazation

In [ ]:
a = np.array([[1,2,3],[4,5,6]], order='F') # column major order
print(a)

[[1 2 3]
 [4 5 6]]


In [43]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [47]:
%%timeit
np.fromfunction(lambda i, j: i + j, (10000, 10000), dtype=int)

895 ms ± 58.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [48]:
%%timeit
n = 2300
a = np.empty((n,n), dtype=int)
for i in range(0,n):
    for j in range(0,n):
        a[i][j]=i+j

825 ms ± 9.85 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [53]:
%%timeit
def g(i):
    if (np.all(i == 0)):
        return 0
    return g(i // 2) + i

def f(i,j):
    return g(i) + g(j)

a = np.fromfunction(f, (2000, 2000), dtype=int)

822 ms ± 134 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
